# Generated by Django 5.0

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signup_date', models.DateTimeField(auto_now_add=True)),
                ('email_verified_at', models.DateTimeField(blank=True, null=True)),
                ('first_price_report_at', models.DateTimeField(blank=True, null=True)),
                ('total_price_reports', models.PositiveIntegerField(default=0)),
                ('total_watchlist_additions', models.PositiveIntegerField(default=0)),
                ('total_shopping_lists', models.PositiveIntegerField(default=0)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
                ('login_count', models.PositiveIntegerField(default=0)),
                ('last_activity_at', models.DateTimeField(auto_now=True)),
                ('is_active_user', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Analytics',
            },
        ),
        migrations.CreateModel(
            name='DailySignupMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total_signups', models.PositiveIntegerField(default=0)),
                ('verified_signups', models.PositiveIntegerField(default=0)),
                ('price_contributor_signups', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Daily Signup Metrics',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='UserActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='useractivitylog',
            index=models.Index(fields=['user', 'activity_type', 'timestamp'], name='analytics_useractivitylog_user_activity_timestamp_idx'),
        ),
        migrations.AddIndex(
            model_name='useractivitylog',
            index=models.Index(fields=['activity_type', 'timestamp'], name='analytics_useractivitylog_activity_timestamp_idx'),
        ),
    ]
