# Generated by Django 5.2.1 on 2026-03-08 01:35

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsDashboardProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Analytics Dashboard',
                'verbose_name_plural': 'Analytics Dashboard',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RenameIndex(
            model_name='useractivitylog',
            new_name='analytics_u_user_id_0a0423_idx',
            old_name='analytics_useractivitylog_user_activity_timestamp_idx',
        ),
        migrations.RenameIndex(
            model_name='useractivitylog',
            new_name='analytics_u_activit_7c778d_idx',
            old_name='analytics_useractivitylog_activity_timestamp_idx',
        ),
    ]
