# Generated by Django 5.2.11 on 2026-04-29 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_analyticsdashboardproxy_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnalyticsDashboardProxy',
        ),
    ]
