# Generated by Django 5.2.15 on 2026-07-01 01:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0004_dashboardaccess"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteVisit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("visitor_key", models.CharField(db_index=True, max_length=80)),
                ("path", models.CharField(max_length=500)),
                (
                    "page_type",
                    models.CharField(
                        choices=[
                            ("page", "Page"),
                            ("about", "About page"),
                            ("price_detail", "Price detail"),
                        ],
                        db_index=True,
                        default="page",
                        max_length=30,
                    ),
                ),
                ("referrer", models.CharField(blank=True, max_length=500)),
                ("user_agent", models.CharField(blank=True, max_length=500)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "timestamp",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="site_visits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["timestamp", "page_type"],
                        name="analytics_s_timesta_6a4547_idx",
                    ),
                    models.Index(
                        fields=["visitor_key", "timestamp"],
                        name="analytics_s_visitor_82be57_idx",
                    ),
                ],
            },
        ),
    ]
