# Generated by Django 5.2.16 on 2026-07-15 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CabDriver",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "whatsapp_number",
                    models.CharField(db_index=True, max_length=32, unique=True),
                ),
                ("display_name", models.CharField(max_length=120)),
                (
                    "vehicle_type",
                    models.CharField(
                        choices=[
                            ("taxi", "Taxi"),
                            ("pmv", "PMV"),
                            ("informal", "Informal"),
                        ],
                        max_length=20,
                    ),
                ),
                ("vehicle_make_model", models.CharField(blank=True, max_length=120)),
                ("vehicle_plate", models.CharField(max_length=40)),
                (
                    "profile_photo",
                    models.ImageField(
                        blank=True, upload_to="transport_index/profile_photos/"
                    ),
                ),
                (
                    "vehicle_photo",
                    models.ImageField(
                        blank=True, upload_to="transport_index/vehicle_photos/"
                    ),
                ),
                ("bio", models.CharField(blank=True, max_length=300)),
                ("home_area", models.CharField(blank=True, max_length=120)),
                (
                    "profile_completeness",
                    models.CharField(
                        choices=[("minimal", "Minimal"), ("complete", "Complete")],
                        default="minimal",
                        max_length=20,
                    ),
                ),
                ("is_verified", models.BooleanField(default=False)),
                ("is_active_listing", models.BooleanField(default=True)),
                (
                    "slug",
                    models.SlugField(
                        blank=True, editable=False, max_length=160, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["display_name"],
            },
        ),
        migrations.CreateModel(
            name="CabStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("area_label", models.CharField(blank=True, max_length=120)),
                (
                    "availability",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("busy", "Busy"),
                            ("offline", "Offline"),
                        ],
                        default="offline",
                        max_length=20,
                    ),
                ),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "driver",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status",
                        to="transport_index.cabdriver",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "cab statuses",
            },
        ),
    ]
