# Generated by Django 5.2.16 on 2026-07-15 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transport_index", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LLMFallbackLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("input_text", models.TextField()),
                ("extracted_intent", models.CharField(blank=True, max_length=120)),
                ("raw_response", models.JSONField(blank=True, default=dict)),
                ("input_tokens", models.PositiveIntegerField(default=0)),
                ("output_tokens", models.PositiveIntegerField(default=0)),
                (
                    "estimated_cost_usd",
                    models.DecimalField(decimal_places=6, default=0, max_digits=10),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RouterEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(blank=True, db_index=True, max_length=32),
                ),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("location_update", "Driver location update"),
                            ("keyword_match", "Keyword match"),
                            ("wizard_step", "Wizard step"),
                            ("rider_location", "Rider location search"),
                            ("gazetteer_hit", "Gazetteer hit"),
                            ("llm_fallback", "LLM fallback"),
                            ("unhandled", "Unhandled"),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                ("message_type", models.CharField(blank=True, max_length=32)),
                ("detail", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ContactAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contact_attempts",
                        to="transport_index.cabdriver",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
