# Generated by Django 5.2.16 on 2026-07-15 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transport_index", "0002_llmfallbacklog_routerevent_contactattempt"),
    ]

    operations = [
        migrations.CreateModel(
            name="WhatsAppMessageLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[("outbound", "Outbound")],
                        default="outbound",
                        max_length=16,
                    ),
                ),
                ("recipient", models.CharField(db_index=True, max_length=32)),
                ("message_type", models.CharField(max_length=32)),
                (
                    "status",
                    models.CharField(
                        choices=[("sent", "Sent"), ("failed", "Failed")],
                        db_index=True,
                        max_length=16,
                    ),
                ),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("response", models.JSONField(blank=True, default=dict)),
                ("error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
