# Generated by Django 6.0.5 on 2026-05-26 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_profile_email_verification_sent_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="deletion_notifications_enabled",
            field=models.BooleanField(default=True),
        ),
    ]
