# Generated by Django 5.2.1 on 2026-04-07 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        # Fresh start - this will be the only migration after database reset
        migrations.CreateModel(
            name='pricereport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey('core.Product', on_delete=models.CASCADE, related_name='price_reports')),
                ('business', models.ForeignKey('core.Business', on_delete=models.SET_NULL, null=True, blank=True, related_name='price_reports')),
                ('business_branch', models.ForeignKey('core.BusinessBranch', on_delete=models.SET_NULL, null=True, blank=True, related_name='price_reports')),
                ('user', models.ForeignKey('auth.User', on_delete=models.CASCADE, related_name='price_reports')),
                ('last_edited_by', models.ForeignKey('auth.User', on_delete=models.SET_NULL, null=True, blank=True, related_name='edited_price_reports')),
                ('price', models.DecimalField(max_digits=12, decimal_places=2)),
                ('currency', models.CharField(max_length=3, default='PGK')),
                ('image', models.ImageField(upload_to='price_report_images/', null=True, blank=True)),
                ('latitude', models.FloatField(null=True, blank=True)),
                ('longitude', models.FloatField(null=True, blank=True)),
                ('observed_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
                ('h3_res9', models.CharField(max_length=16, null=True, blank=True, db_index=True)),
                ('h3_res8', models.CharField(max_length=16, null=True, blank=True, db_index=True)),
                ('marked_for_deletion', models.BooleanField(default=False)),
                ('marked_for_deletion_by', models.ForeignKey('auth.User', on_delete=models.SET_NULL, null=True, blank=True, related_name='marked_for_deletion_reports')),
                ('marked_for_deletion_at', models.DateTimeField(null=True, blank=True)),
                ('deletion_reason', models.TextField(blank=True)),
                ('deletion_votes', models.ManyToManyField('auth.User', related_name='deletion_voted_reports', blank=True)),
                ('ocr_processed', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-observed_at'],
            },
        ),
    ]
