# Generated by Django 5.2.11 on 2026-04-26 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pricereport',
            options={'ordering': ['-updated_at', '-observed_at']},
        ),
        migrations.AlterField(
            model_name='pricereport',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
    ]
