# Generated by Django 5.2.11 on 2026-02-26 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricereport',
            name='h3_res8',
            field=models.CharField(blank=True, db_index=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='pricereport',
            name='h3_res9',
            field=models.CharField(blank=True, db_index=True, max_length=16, null=True),
        ),
    ]
