# Generated by Django 5.2.11 on 2026-02-26 05:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_business_pricereport_business'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pricereport',
            name='last_edited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edited_price_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('new_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('old_currency', models.CharField(blank=True, max_length=3, null=True)),
                ('new_currency', models.CharField(default='PGK', max_length=3)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('price_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='core.pricereport')),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
    ]
