# Generated by Codex on 2026-06-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_comment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(
                choices=[
                    ('general', 'General'),
                    ('comment', 'Comment'),
                    ('reply', 'Reply'),
                    ('comment_like', 'Comment Like'),
                    ('deletion_mark', 'Deletion Mark'),
                ],
                default='general',
                max_length=32,
            ),
        ),
    ]
