# Generated by Django 5.2.1 on 2026-03-03 02:37

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_business_image_pricereport_image_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=75, scale=None, size=[1000, 1000], upload_to='business_images/'),
        ),
        migrations.AlterField(
            model_name='pricereport',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=75, scale=None, size=[1000, 1000], upload_to='price_report_images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=75, scale=None, size=[1000, 1000], upload_to='product_images/'),
        ),
    ]
