# Generated by Django 5.2.15 on 2026-06-12 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0001_initial"),
        ("core", "0007_businessrating_pricereportrating"),
    ]

    operations = [
        migrations.AddField(
            model_name="business",
            name="business_subcategory",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="businesses",
                to="categories.businesssubcategory",
            ),
        ),
        migrations.AddField(
            model_name="pricereport",
            name="subcategory",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="price_reports",
                to="categories.subcategory",
            ),
        ),
    ]
