# Generated by Django 5.2.1 on 2026-06-14 11:52

import django.db.models.deletion
import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_business_business_subcategory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceReportPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', django_resized.forms.ResizedImageField(crop=None, force_format='JPEG', keep_meta=True, quality=75, scale=None, size=[1000, 1000], upload_to='price_report_images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('price_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='core.pricereport')),
            ],
            options={
                'verbose_name': 'Price Report Photo',
                'verbose_name_plural': 'Price Report Photos',
                'ordering': ['order', 'uploaded_at'],
            },
        ),
    ]
