# Generated by Django 5.2.1 on 2026-03-05 00:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_business_image_alter_pricereport_image_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pricereport',
            name='deletion_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='pricereport',
            name='deletion_votes',
            field=models.ManyToManyField(blank=True, related_name='deletion_voted_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pricereport',
            name='marked_for_deletion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pricereport',
            name='marked_for_deletion_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pricereport',
            name='marked_for_deletion_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marked_for_deletion_reports', to=settings.AUTH_USER_MODEL),
        ),
    ]
