# Generated by Django 5.2.15 on 2026-07-01 10:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_pricereportphoto"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="pricereport",
            name="duplicate_trust_votes",
            field=models.ManyToManyField(
                blank=True,
                related_name="trusted_duplicate_reports",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="pricereport",
            name="duplicate_verify_votes",
            field=models.ManyToManyField(
                blank=True,
                related_name="verified_duplicate_reports",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="pricereport",
            name="duplicated_from",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="duplicates",
                to="core.pricereport",
            ),
        ),
    ]
