# Generated by Django 5.2.1 on 2026-03-08 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ]
    
    operations = [
        migrations.AddField(
            model_name='business',
            name='details',
            field=models.TextField(blank=True, help_text='Additional information about the business', null=True),
        ),
    ]
