# Generated by Django 5.2.16 on 2026-07-27

import core.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_notification_guide_targets'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkImportSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('inventory_file', models.FileField(upload_to=core.models.bulk_import_inventory_path)),
                ('inventory_filename', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('inventory', 'Inventory upload'), ('photos', 'Photo upload'), ('review', 'Review'), ('processing', 'Importing'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='inventory', max_length=20)),
                ('current_stage', models.CharField(blank=True, max_length=80)),
                ('progress_percent', models.PositiveSmallIntegerField(default=0)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('valid_rows', models.PositiveIntegerField(default=0)),
                ('invalid_rows', models.PositiveIntegerField(default=0)),
                ('total_images', models.PositiveIntegerField(default=0)),
                ('matched_images', models.PositiveIntegerField(default=0)),
                ('unmatched_images', models.PositiveIntegerField(default=0)),
                ('duplicate_images', models.PositiveIntegerField(default=0)),
                ('duplicate_products', models.PositiveIntegerField(default=0)),
                ('products_created', models.PositiveIntegerField(default=0)),
                ('price_reports_created', models.PositiveIntegerField(default=0)),
                ('photos_processed', models.PositiveIntegerField(default=0)),
                ('warnings', models.JSONField(blank=True, default=list)),
                ('errors', models.JSONField(blank=True, default=list)),
                ('last_error', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField()),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulk_import_sessions', to='core.business')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulk_import_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BulkImportRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.PositiveIntegerField()),
                ('sku', models.CharField(blank=True, db_index=True, max_length=120)),
                ('barcode', models.CharField(blank=True, db_index=True, max_length=120)),
                ('product_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('brand', models.CharField(blank=True, max_length=255)),
                ('category_name', models.CharField(blank=True, max_length=255)),
                ('unit', models.CharField(blank=True, max_length=80)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('currency', models.CharField(default='PGK', max_length=3)),
                ('stock_quantity', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('notes', models.TextField(blank=True)),
                ('tags', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('valid', 'Valid'), ('invalid', 'Invalid'), ('imported', 'Imported'), ('failed', 'Failed')], db_index=True, default='valid', max_length=12)),
                ('validation_errors', models.JSONField(blank=True, default=list)),
                ('imported_at', models.DateTimeField(blank=True, null=True)),
                ('price_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bulk_import_rows', to='core.pricereport')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bulk_import_rows', to='core.product')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='core.bulkimportsession')),
            ],
            options={
                'ordering': ['row_number'],
            },
        ),
        migrations.CreateModel(
            name='BulkImportImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to=core.models.bulk_import_staging_path)),
                ('original_filename', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=100)),
                ('size_bytes', models.PositiveBigIntegerField(default=0)),
                ('content_hash', models.CharField(db_index=True, max_length=64)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('matched', 'Matched'), ('unmatched', 'Unmatched'), ('duplicate', 'Duplicate'), ('skipped', 'Skipped'), ('rejected', 'Rejected'), ('imported', 'Imported')], db_index=True, default='uploaded', max_length=12)),
                ('match_method', models.CharField(blank=True, max_length=40)),
                ('confidence', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('is_primary', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('warning', models.TextField(blank=True)),
                ('error', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('imported_at', models.DateTimeField(blank=True, null=True)),
                ('duplicate_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicates', to='core.bulkimportimage')),
                ('matched_row', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matched_images', to='core.bulkimportrow')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.bulkimportsession')),
            ],
            options={
                'ordering': ['uploaded_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='BusinessInventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(blank=True, db_index=True, max_length=120)),
                ('barcode', models.CharField(blank=True, db_index=True, max_length=120)),
                ('description', models.TextField(blank=True)),
                ('brand', models.CharField(blank=True, max_length=255)),
                ('unit', models.CharField(blank=True, max_length=80)),
                ('stock_quantity', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='core.business')),
                ('last_import_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_items', to='core.bulkimportsession')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_inventory_items', to='core.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original', models.ImageField(upload_to=core.models.product_image_original_path)),
                ('medium', models.ImageField(blank=True, upload_to=core.models.product_image_medium_path)),
                ('thumbnail', models.ImageField(blank=True, upload_to=core.models.product_image_thumbnail_path)),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('content_hash', models.CharField(db_index=True, max_length=64)),
                ('is_primary', models.BooleanField(db_index=True, default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_images', to='core.business')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalog_images', to='core.product')),
            ],
            options={
                'ordering': ['sort_order', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='bulkimportsession',
            index=models.Index(fields=['user', 'status', '-created_at'], name='core_bulkim_user_id_fb53b7_idx'),
        ),
        migrations.AddIndex(
            model_name='bulkimportsession',
            index=models.Index(fields=['expires_at'], name='core_bulkim_expires_a47aab_idx'),
        ),
        migrations.AddIndex(
            model_name='bulkimportrow',
            index=models.Index(fields=['session', 'status', 'row_number'], name='core_bulkim_session_6bd553_idx'),
        ),
        migrations.AddIndex(
            model_name='bulkimportrow',
            index=models.Index(fields=['session', 'sku'], name='core_bulkim_session_f20998_idx'),
        ),
        migrations.AddIndex(
            model_name='bulkimportrow',
            index=models.Index(fields=['session', 'barcode'], name='core_bulkim_session_167587_idx'),
        ),
        migrations.AddConstraint(
            model_name='bulkimportrow',
            constraint=models.UniqueConstraint(fields=('session', 'row_number'), name='unique_bulk_import_row'),
        ),
        migrations.AddIndex(
            model_name='bulkimportimage',
            index=models.Index(fields=['session', 'status'], name='core_bulkim_session_599900_idx'),
        ),
        migrations.AddIndex(
            model_name='bulkimportimage',
            index=models.Index(fields=['session', 'content_hash'], name='core_bulkim_session_c8e6dc_idx'),
        ),
        migrations.AddIndex(
            model_name='bulkimportimage',
            index=models.Index(fields=['matched_row', 'is_primary', 'sort_order'], name='core_bulkim_matched_ff720f_idx'),
        ),
        migrations.AddIndex(
            model_name='businessinventoryitem',
            index=models.Index(fields=['business', 'sku'], name='core_busine_busines_4a5c83_idx'),
        ),
        migrations.AddIndex(
            model_name='businessinventoryitem',
            index=models.Index(fields=['business', 'barcode'], name='core_busine_busines_ab7085_idx'),
        ),
        migrations.AddConstraint(
            model_name='businessinventoryitem',
            constraint=models.UniqueConstraint(fields=('business', 'product'), name='unique_business_inventory_product'),
        ),
        migrations.AddIndex(
            model_name='productimage',
            index=models.Index(fields=['product', 'is_primary', 'sort_order'], name='core_produc_product_39022d_idx'),
        ),
        migrations.AddIndex(
            model_name='productimage',
            index=models.Index(fields=['business', 'content_hash'], name='core_produc_busines_81c3fc_idx'),
        ),
    ]
