# Generated by Django 5.2.1 on 2026-03-15 02:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_add_product_alias'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='productalias',
            name='signature',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name='productalias',
            index=models.Index(fields=['signature'], name='core_produc_signatu_c7b7f2_idx'),
        ),
    ]
