# Generated by Django 5.2.1 on 2026-03-15 02:17

from django.db import migrations


def populate_signatures(apps, schema_editor):
    """Populate signature field for existing ProductAlias records"""
    ProductAlias = apps.get_model('core', 'ProductAlias')
    
    for alias in ProductAlias.objects.all():
        # Use the same logic as the model method
        normalized = ' '.join(alias.alias_name.lower().split())
        normalized = normalized.replace('-', ' ')
        normalized = ' '.join(normalized.split())
        
        # Extract components and create signature
        import re
        size_patterns = [
            r'(\d+(?:\.\d+)?)\s*(kg|g|l|ml|oz|lb|pcs|pc|pack|bottle|can|box|bag)',
            r'(\d+(?:\.\d+)?)\s*(kilogram|gram|liter|milliliter|ounce|pound|piece|pieces)',
            r'(\d+(?:\.\d+)?)\s*(x\s*\d+)',
        ]
        
        size_match = None
        size_info = None
        
        for pattern in size_patterns:
            match = re.search(pattern, normalized)
            if match:
                size_match = match
                size_info = match.group(0)
                break
        
        if size_match:
            product_name = normalized.replace(size_info, '').strip()
            signature = f"{product_name} {size_info}"
        else:
            signature = normalized
        
        # Clean up the signature
        signature = ' '.join(signature.lower().split())
        signature = re.sub(r'[^\w\s]', ' ', signature)
        signature = ' '.join(signature.split())
        
        alias.signature = signature
        alias.save(update_fields=['signature'])


def reverse_populate_signatures(apps, schema_editor):
    """Reverse migration - clear signatures"""
    ProductAlias = apps.get_model('core', 'ProductAlias')
    ProductAlias.objects.all().update(signature=None)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_add_product_signature'),
    ]

    operations = [
        migrations.RunPython(populate_signatures, reverse_populate_signatures),
    ]
