# Generated by Django 5.2.1 on 2026-03-15 02:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_add_business_alias'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Branch name (e.g., 'Port Moresby Main', 'Waigani Branch')", max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('address', models.TextField(blank=True, help_text='Full address of this branch', null=True)),
                ('latitude', models.FloatField(blank=True, help_text='Branch latitude for mapping', null=True)),
                ('longitude', models.FloatField(blank=True, help_text='Branch longitude for mapping', null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('is_main_branch', models.BooleanField(default=False, help_text='Mark as the main/head office branch')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('canonical_business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='core.business')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['is_main_branch', 'name'],
            },
        ),
        migrations.AddField(
            model_name='pricereport',
            name='business_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='price_reports', to='core.businessbranch'),
        ),
        migrations.AddIndex(
            model_name='businessbranch',
            index=models.Index(fields=['canonical_business', 'is_active'], name='core_busine_canonic_86d436_idx'),
        ),
        migrations.AddIndex(
            model_name='businessbranch',
            index=models.Index(fields=['latitude', 'longitude'], name='core_busine_latitud_e2d476_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='businessbranch',
            unique_together={('canonical_business', 'slug')},
        ),
    ]
