# Generated by Django 5.2.11 on 2026-04-07 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_add_business_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricereport',
            name='ocr_processed',
            field=models.BooleanField(default=True),
        ),
    ]
