# Generated by Django 5.2.1 on 2026-04-07 12:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_add_business_branch'),
    ]

    operations = [
    ]
