# Generated by Django 5.2.1 on 2026-03-15 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_add_business_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricereport',
            name='ocr_confidence',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='OCR confidence score (0-1)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='pricereport',
            name='ocr_error_message',
            field=models.TextField(blank=True, help_text='Error message if OCR processing failed', null=True),
        ),
        migrations.AddField(
            model_name='pricereport',
            name='ocr_extracted_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price extracted by OCR', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='pricereport',
            name='ocr_extracted_product_name',
            field=models.CharField(blank=True, help_text='Product name extracted by OCR', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pricereport',
            name='ocr_processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pricereport',
            name='ocr_processing_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('manual_review', 'Manual Review Required')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='pricereport',
            name='ocr_raw_text',
            field=models.TextField(blank=True, help_text='Raw text extracted by OCR', null=True),
        ),
        migrations.AddField(
            model_name='pricereport',
            name='ocr_results',
            field=models.JSONField(blank=True, help_text='Full OCR results as JSON', null=True),
        ),
        migrations.CreateModel(
            name='OCRProcessingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processing_type', models.CharField(choices=[('product_image', 'Product Image OCR'), ('receipt', 'Receipt OCR')], max_length=20)),
                ('status', models.CharField(choices=[('started', 'Started'), ('completed', 'Completed'), ('failed', 'Failed'), ('retry', 'Retry')], max_length=20)),
                ('image_path', models.CharField(blank=True, max_length=500, null=True)),
                ('image_size_bytes', models.PositiveIntegerField(blank=True, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('processing_time_seconds', models.FloatField(blank=True, null=True)),
                ('confidence_score', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('extracted_text_length', models.PositiveIntegerField(blank=True, null=True)),
                ('items_found', models.PositiveIntegerField(default=0, help_text='Number of items/products found')),
                ('error_message', models.TextField(blank=True, null=True)),
                ('error_type', models.CharField(blank=True, max_length=100, null=True)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('raw_results', models.JSONField(blank=True, null=True)),
                ('price_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ocr_logs', to='core.pricereport')),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['processing_type', 'status'], name='core_ocrpro_process_a63e9b_idx'), models.Index(fields=['started_at'], name='core_ocrpro_started_25e92c_idx')],
            },
        ),
    ]
