# Generated by Django 5.2.1 on 2026-04-07 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_add_business_branch'),
        ('core', '0016_handle_existing_ocr_field'),
    ]

    operations = [
    ]
