# Generated by Django 5.2.1 on 2026-04-07 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_merge_ocr_field_conflicts'),
    ]

    operations = [
        # This migration handles any remaining conflicts gracefully
        # It's a no-op migration that just marks the conflicts as resolved
        migrations.RunSQL(
            sql="SELECT 1;",
            reverse_sql="SELECT 1;"
        ),
    ]
