# Generated by Django 5.2.1 on 2026-04-07 13:15

from django.db import migrations, connection


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_final_merge_conflicts'),
    ]

    operations = [
        # Clean up any conflicting migrations in production database
        migrations.RunSQL(
            sql="""
                -- Remove any trace of conflicting migrations from django_migrations table
                DELETE FROM django_migrations 
                WHERE app = 'core' 
                AND name IN (
                    '0009_pricereport_deletion_reason_and_more',
                    '0016_add_ocr_processed_field',
                    '0016_handle_existing_ocr_field'
                );
            """,
            reverse_sql="""
                -- No reverse needed for cleanup
                INSERT INTO django_migrations (app, name, applied) 
                VALUES ('core', '0009_pricereport_deletion_reason_and_more', '1970-01-01');
                INSERT INTO django_migrations (app, name, applied) 
                VALUES ('core', '0016_add_ocr_processed_field', '1970-01-01');
                INSERT INTO django_migrations (app, name, applied) 
                VALUES ('core', '0016_handle_existing_ocr_field', '1970-01-01');
            """
        ),
    ]
